"""new fields in user model

Revision ID: 682bc1db9a5c
Revises: f940c909564d
Create Date: 2020-09-26 09:32:09.268196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682bc1db9a5c'
down_revision = 'f940c909564d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image')
    # ### end Alembic commands ###
