"""new fields in book  model

Revision ID: 7989ed950fca
Revises: 4efba33da7f0
Create Date: 2020-09-28 14:32:26.325507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7989ed950fca'
down_revision = '4efba33da7f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'image')
    # ### end Alembic commands ###
